In [2]:
import pandas as pd
df = pd.read_csv ('salaries_by_college_major.csv')

In [3]:
df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business

In [7]:
df.shape

(51, 6)

In [8]:
df.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='object')

In [9]:
df.isna

<bound method DataFrame.isna of                      Undergraduate Major  Starting Median Salary  \
0                             Accounting                 46000.0
1                  Aerospace Engineering                 57700.0
2                            Agriculture                 42600.0
3                           Anthropology                 36800.0
4                           Architecture                 41600.0
5                            Art History                 35800.0
6                                Biology                 38800.0
7                    Business Management                 43000.0
8                   Chemical Engineering                 63200.0
9                              Chemistry                 42600.0
10                     Civil Engineering                 53900.0
11                        Communications                 38100.0
12                  Computer Engineering                 61400.0
13                      Computer Science                 55900.0
14                          Construction                 53700.0
15                      Criminal Justice                 35000.0
16                                 Drama                 35900.0
17                             Economics                 50100.0
18                             Education                 34900.0
19                Electrical Engineering                 60900.0
20                               English                 38000.0
21                                  Film                 37900.0
22                               Finance                 47900.0
23                              Forestry                 39100.0
24                             Geography                 41200.0
25                               Geology                 43500.0
26                        Graphic Design                 35700.0
27            Health Care Administration                 38800.0
28                               History                 39200.0
29                 Hospitality & Tourism                 37800.0
30                Industrial Engineering                 57700.0
31           Information Technology (IT)                 49100.0
32                       Interior Design                 36100.0
33               International Relations                 40900.0
34                            Journalism                 35600.0
35  Management Information Systems (MIS)                 49200.0
36                             Marketing                 40800.0
37                                  Math                 45400.0
38                Mechanical Engineering                 57900.0
39                                 Music                 35900.0
40                               Nursing                 54200.0
41                             Nutrition                 39900.0
42                            Philosophy                 39900.0
43                   Physician Assistant                 74300.0
44                               Physics                 50300.0
45                     Political Science                 40800.0
46                            Psychology                 35900.0
47                              Religion                 34100.0
48                             Sociology                 36500.0
49                               Spanish                 34000.0
50                 Source: PayScale Inc.                     NaN

    Mid-Career Median Salary  Mid-Career 10th Percentile Salary  \
0                    77100.0                            42200.0
1                   101000.0                            64300.0
2                    71900.0                            36300.0
3                    61500.0                            33800.0
4                    76800.0                            50600.0
5                    64900.0                            28800.0
6                    64800.0                            36900.0
7                    72100.0                            38800.0
8                   107000.0                            71900.0
9                    79900.0                            45300.0
10                   90500.0                            63400.0
11                   70000.0                            37500.0
12                  105000.0                            66100.0
13                   95500.0                            56000.0
14                   88900.0                            56300.0
15                   56300.0                            32200.0
16                   56900.0                            36700.0
17                   98600.0                            50600.0
18                   52000.0                            29300.0
19                  103000.0                            69300.0
20                   64700.0                            33400.0
21                   68500.0                            33900.0
22                   88300.0                            47200.0
23                   62600.0                            41000.0
24                   65500.0                            40000.0
25                   79500.0                            45000.0
26                   59800.0                            36000.0
27                   60600.0                            34600.0
28                   71000.0                            37000.0
29                   57500.0                            35500.0
30                   94700.0                            57100.0
31                   74800.0                            44500.0
32                   53200.0                            35700.0
33                   80900.0                            38200.0
34                   66700.0                            38400.0
35                   82300.0                            45300.0
36                   79600.0                            42100.0
37                   92400.0                            45200.0
38                   93600.0                            63700.0
39                   55000.0                            26700.0
40                   67000.0                            47600.0
41                   55300.0                            33900.0
42                   81200.0                            35500.0
43                   91700.0                            66400.0
44                   97300.0                            56000.0
45                   78200.0                            41200.0
46                   60400.0                            31600.0
47                   52000.0                            29700.0
48                   58200.0                            30700.0
49                   53100.0                            31000.0
50                       NaN                                NaN

    Mid-Career 90th Percentile Salary     Group
0                            152000.0  Business
1                            161000.0      STEM
2                            150000.0  Business
3                            138000.0      HASS
4                            136000.0  Business
5                            125000.0      HASS
6                            135000.0      STEM
7                            147000.0  Business
8                            194000.0      STEM
9                            148000.0      STEM
10                           148000.0      STEM
11                           143000.0      HASS
12                           162000.0      STEM
13                           154000.0      STEM
14                           171000.0  Business
15                           107000.0      HASS
16                           153000.0      HASS
17                           210000.0  Business
18                           102000.0      HASS
19                           168000.0      STEM
20                           133000.0      HASS
21                           136000.0      HASS
22                           195000.0  Business
23                           111000.0  Business
24                           132000.0      HASS
25                           156000.0      STEM
26                           112000.0      HASS
27                           101000.0  Business
28                           149000.0      HASS
29                           124000.0  Business
30                           173000.0      STEM
31                           129000.0      STEM
32                           107000.0      HASS
33                           157000.0      HASS
34                           145000.0      HASS
35                           146000.0      STEM
36                           175000.0  Business
37                           183000.0      STEM
38                           163000.0      STEM
39                           134000.0      HASS
40                            98300.0  Business
41                            99200.0      HASS
42                           168000.0      HASS
43                           124000.0      STEM
44                           178000.0      STEM
45                           168000.0      HASS
46                           127000.0      HASS
47                            96400.0      HASS
48                           118000.0      HASS
49                            96400.0      HASS
50                                NaN       NaN  >

In [10]:
df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN

In [4]:
clean_df = df.dropna()

In [5]:
clean_df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS

In [14]:
clean_df['Starting Median Salary']

0     46000.0
1     57700.0
2     42600.0
3     36800.0
4     41600.0
5     35800.0
6     38800.0
7     43000.0
8     63200.0
9     42600.0
10    53900.0
11    38100.0
12    61400.0
13    55900.0
14    53700.0
15    35000.0
16    35900.0
17    50100.0
18    34900.0
19    60900.0
20    38000.0
21    37900.0
22    47900.0
23    39100.0
24    41200.0
25    43500.0
26    35700.0
27    38800.0
28    39200.0
29    37800.0
30    57700.0
31    49100.0
32    36100.0
33    40900.0
34    35600.0
35    49200.0
36    40800.0
37    45400.0
38    57900.0
39    35900.0
40    54200.0
41    39900.0
42    39900.0
43    74300.0
44    50300.0
45    40800.0
46    35900.0
47    34100.0
48    36500.0
49    34000.0
Name: Starting Median Salary, dtype: float64

In [15]:
clean_df['Starting Median Salary'].max()

74300.0

In [19]:
clean_df['Starting Median Salary'].idxmax()

43

In [22]:
clean_df['Undergraduate Major'][43]

'Physician Assistant'

In [24]:
clean_df.loc[43]

Undergraduate Major                  Physician Assistant
Starting Median Salary                           74300.0
Mid-Career Median Salary                         91700.0
Mid-Career 10th Percentile Salary                66400.0
Mid-Career 90th Percentile Salary               124000.0
Group                                               STEM
Name: 43, dtype: object

In [25]:
# -------------------------------------------------------------------------------------------------
# What college major has the highest mid-career salary? How much do graduates with this major earn?
# -------------------------------------------------------------------------------------------------

# Highest salary:

clean_df['Mid-Career Median Salary'].max()

107000.0

In [26]:
# Index of the major:

clean_df['Mid-Career Median Salary'].idxmax()

8

In [28]:
# Name of the major:

clean_df['Undergraduate Major'][8]

'Chemical Engineering'

In [29]:
# -------------------------------------------------------------------------------------------------
# Which college major has the lowest starting salary and how much do graduates earn after university?
# -------------------------------------------------------------------------------------------------

# Lowest Median Salary

clean_df['Starting Median Salary'].min()

34000.0

In [31]:
# Index of the major with lowest median salary:

clean_df['Starting Median Salary'].idxmin()

49

In [32]:
# Name of the major:

clean_df['Undergraduate Major'][49]

'Spanish'

In [34]:
# -------------------------------------------------------------------------------------------------------------
# Which college major has the lowest mid-career salary and how much can people expect to earn with this degree?
# -------------------------------------------------------------------------------------------------------------

# Lowest mid-career salary:

clean_df['Mid-Career Median Salary'].min()

52000.0

In [35]:
# Index of the major

clean_df['Mid-Career Median Salary'].idxmin()

18

In [36]:
# Salary expectations (low):

clean_df['Mid-Career 10th Percentile Salary'][18]

29300.0

In [38]:
# Salary expectations (high):

clean_df['Mid-Career 90th Percentile Salary'][18]

102000.0

In [6]:
#  Difference between the earnings of the 10th and 90th percentile:

clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']

0     109800.0
1      96700.0
2     113700.0
3     104200.0
4      85400.0
5      96200.0
6      98100.0
7     108200.0
8     122100.0
9     102700.0
10     84600.0
11    105500.0
12     95900.0
13     98000.0
14    114700.0
15     74800.0
16    116300.0
17    159400.0
18     72700.0
19     98700.0
20     99600.0
21    102100.0
22    147800.0
23     70000.0
24     92000.0
25    111000.0
26     76000.0
27     66400.0
28    112000.0
29     88500.0
30    115900.0
31     84500.0
32     71300.0
33    118800.0
34    106600.0
35    100700.0
36    132900.0
37    137800.0
38     99300.0
39    107300.0
40     50700.0
41     65300.0
42    132500.0
43     57600.0
44    122000.0
45    126800.0
46     95400.0
47     66700.0
48     87300.0
49     65400.0
dtype: float64

In [7]:
# Insert new column into our clean dataset:

spread_col = clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']
clean_df.insert(1, 'Spread', spread_col)
clean_df.head()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,109800.0,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,96700.0,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,113700.0,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,104200.0,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,85400.0,41600.0,76800.0,50600.0,136000.0,Business

In [9]:
# Calculate Majors with lowest risk:

low_risk = clean_df.sort_values('Spread')
low_risk[['Undergraduate Major', 'Spread']].head()

           Undergraduate Major   Spread
40                     Nursing  50700.0
43         Physician Assistant  57600.0
41                   Nutrition  65300.0
49                     Spanish  65400.0
27  Health Care Administration  66400.0

In [11]:
# Calculate Majors with the highest potential:

highest_potential = clean_df.sort_values('Mid-Career 90th Percentile Salary', ascending=False)
highest_potential[['Undergraduate Major', 'Mid-Career 90th Percentile Salary']].head()

     Undergraduate Major  Mid-Career 90th Percentile Salary
17             Economics                           210000.0
22               Finance                           195000.0
8   Chemical Engineering                           194000.0
37                  Math                           183000.0
44               Physics                           178000.0

In [12]:
# Calculate Majors with the highest spread:

highest_spread = clean_df.sort_values('Spread', ascending=False)
highest_spread[['Undergraduate Major', 'Spread']].head()

   Undergraduate Major    Spread
17           Economics  159400.0
22             Finance  147800.0
37                Math  137800.0
36           Marketing  132900.0
42          Philosophy  132500.0

In [13]:
# Count majors by category

clean_df.groupby('Group').count()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,,
Business,12,12,12,12,12,12
HASS,22,22,22,22,22,22
STEM,16,16,16,16,16,16

In [16]:
# Clean pandas format:

pd.options.display.float_format = '{:,.2f}'.format

# Find the mean salaries for each group:
clean_df.groupby('Group').mean()

<ipython-input-16-cbfacd1918e6>:6: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  clean_df.groupby('Group').mean()

,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,
Business,"103,958.33","44,633.33","75,083.33","43,566.67","147,525.00"
HASS,"95,218.18","37,186.36","62,968.18","34,145.45","129,363.64"
STEM,"101,600.00","53,862.50","90,812.50","56,025.00","157,625.00"